### ISSUE TITLE
RuntimeError: dictionary keys changed during iteration on python 3.8

### ISSUE THREAD

**Issue by jqueuniet** [netbox-community/ansible_modules#151]
##### ISSUE TYPE
 - Bug Report

###### Ansible:
2.9.6

###### Netbox:
2.5.13

###### Collection:
0.1.10

##### SUMMARY
With Python 3.8, any kind of usage triggers a RuntimeError

##### STEPS TO REPRODUCE
Any netbox module usage with Python 3.8 as interpreter.

##### EXPECTED RESULTS
The module runs properly.

##### ACTUAL RESULTS
The module crashs with the following traceback:

```
Traceback (most recent call last):
  File "/home/johann/.ansible/tmp/ansible-tmp-1585637538.0733168-104991330799015/AnsiballZ_netbox_virtual_machine.py", line 102, in <module>
    _ansiballz_main()
  File "/home/johann/.ansible/tmp/ansible-tmp-1585637538.0733168-104991330799015/AnsiballZ_netbox_virtual_machine.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/johann/.ansible/tmp/ansible-tmp-1585637538.0733168-104991330799015/AnsiballZ_netbox_virtual_machine.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.netbox.netbox.plugins.modules.netbox_virtual_machine', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.8/runpy.py", line 206, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_netbox_virtual_machine_payload_yn6kv91c/ansible_netbox_virtual_machine_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_virtual_machine.py", line 216, in <module>
  File "/tmp/ansible_netbox_virtual_machine_payload_yn6kv91c/ansible_netbox_virtual_machine_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_virtual_machine.py", line 211, in main
  File "/tmp/ansible_netbox_virtual_machine_payload_yn6kv91c/ansible_netbox_virtual_machine_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_virtualization.py", line 31, in __init__
  File "/tmp/ansible_netbox_virtual_machine_payload_yn6kv91c/ansible_netbox_virtual_machine_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 340, in __init__
  File "/tmp/ansible_netbox_virtual_machine_payload_yn6kv91c/ansible_netbox_virtual_machine_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 392, in _convert_identical_keys
RuntimeError: dictionary keys changed during iteration
```

**Comment by FragmentedPacket** [comment]
Thanks for the submission! I will change the logic and add Python 3.8 to our tests as well.

Hopefully get this done within the next few days.

**Comment by DouglasHeriot** [comment]
I saw this error come up in #145 - the new build with Python 3.8, Ansible dev and Netbox dev https://travis-ci.com/github/netbox-community/ansible_modules/jobs/308284771#L564

We should probably also update the latest release versions build to use Python 3.8.

**Comment by FragmentedPacket** [comment]
@jqueuniet Do you mind checking the attached PR to make sure it works for you using the new code?

**Comment by jqueuniet** [comment]
Works for me by applying the changes to my installed 1.10 code
