### ISSUE TITLE
Error running netbox_manufacturer module

### ISSUE THREAD

**Issue by AmazingRedPanda** [netbox-community/ansible_modules#172]
##### ISSUE TYPE

 - Bug Report

###### Ansible:
ansible --version
ansible 2.9.6

###### Netbox:
Netbox Version v2.7.11

###### Collection:
netbox_manufacturer

##### SUMMARY
Got an error running the playbook 

##### STEPS TO REPRODUCE

```yaml
- name: "Test Netbox modules"
  connection: local
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Create manufacturer within Netbox with only required information
      collections:
        - netbox.netbox
      netbox_manufacturer:
        netbox_url: url
        netbox_token: token
        data:
          name: Test Manufacturer
        state: present
```

##### EXPECTED RESULTS
Add test-manufacturer as manufacturer

##### ACTUAL RESULTS

 PLAY RECAP *********************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 

```
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1586433270.02-76066920195961/AnsiballZ_netbox_manufacturer.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1586433270.02-76066920195961/AnsiballZ_netbox_manufacturer.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1586433270.02-76066920195961/AnsiballZ_netbox_manufacturer.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.netbox.netbox.plugins.modules.netbox_manufacturer', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python2.7/runpy.py", line 188, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_netbox_manufacturer_payload_VKMIs1/ansible_netbox_manufacturer_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_manufacturer.py", line 133, in <module>
  File "/tmp/ansible_netbox_manufacturer_payload_VKMIs1/ansible_netbox_manufacturer_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_manufacturer.py", line 125, in main
  File "/tmp/ansible_netbox_manufacturer_payload_VKMIs1/ansible_netbox_manufacturer_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 748, in __init__
TypeError: super() takes at least 1 argument (0 given)
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1586433270.02-76066920195961/AnsiballZ_netbox_manufacturer.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1586433270.02-76066920195961/AnsiballZ_netbox_manufacturer.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1586433270.02-76066920195961/AnsiballZ_netbox_manufacturer.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.netbox.netbox.plugins.modules.netbox_manufacturer', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python2.7/runpy.py\", line 188, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_netbox_manufacturer_payload_VKMIs1/ansible_netbox_manufacturer_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_manufacturer.py\", line 133, in <module>\n  File \"/tmp/ansible_netbox_manufacturer_payload_VKMIs1/ansible_netbox_manufacturer_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_manufacturer.py\", line 125, in main\n  File \"/tmp/ansible_netbox_manufacturer_payload_VKMIs1/ansible_netbox_manufacturer_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py\", line 748, in __init__\nTypeError: super() takes at least 1 argument (0 given)\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}

```

**Comment by FragmentedPacket** [comment]
This collection requires Python3 and appears you're using Python2

**Comment by AmazingRedPanda** [comment]
I guess we can close the issue you were right.

complementary information: 

On ubuntu with official PPA ansible configured, the package Ansible will install python2.7 as default interpreter and use it even if you have set python3 as default (update alternatives)

I have to use pip3 install ansible for use python3 
or set -e 'ansible_python_interpreter=/usr/bin/python3 when launching playbook.


Maybe theses information could be added as a note for requirements although this information concern ansible configuration .

**Comment by FragmentedPacket** [comment]
Thanks for the info! I don't want to document anything as you stated that is more related to Ansible than specific to these modules.

This issue can serve to help people that do run across the same issue as you in the future though!
