### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by metabsd** [netbox-community/ansible_modules#214]
##### ISSUE TYPE
 - Bug Report

###### Ansible:
2.9.6

###### Netbox:
2.7.11

###### Collection:
0.2.1

##### SUMMARY
Threading error when `interfaces: False`

##### STEPS TO REPRODUCE
```yaml
plugin: netbox.netbox.nb_inventory
validate_certs: False
config_context: True
services: False
interfaces: True
fetch_all: False
group_by:
  - device_roles
  - sites
  - racks
  - tenants
query_filters:
  - role: a_role
  - role: another_role
  - cf_owner: 5
  - status: active
  - tag: dev
timeout: 180
```

##### EXPECTED RESULTS
More speed because I don't fetch 70000 interfaces.

##### ACTUAL RESULTS

The error from Ansible Tower. When I used `interfaces: True` is working but take more and more time.

Short section in the debug log:
```
Fetching: https://URL/api/dcim/interfaces/?limit=0&device_id=4857&device_id=4847&device_id=229&device_id=1698&device_id=1699&device_id=231&device_id=232&device_id=226&device_id=230&device_id=1703
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/awx_60391_azati6wn/requirements_collections/ansible_collections/netbox/netbox/plugins/inventory/nb_inventory.py", line 867, in wrapper
    raise e
  File "/tmp/awx_60391_azati6wn/requirements_collections/ansible_collections/netbox/netbox/plugins/inventory/nb_inventory.py", line 862, in wrapper
    lookup()
  File "/tmp/awx_60391_azati6wn/requirements_collections/ansible_collections/netbox/netbox/plugins/inventory/nb_inventory.py", line 741, in refresh_interfaces
    query_values=self.vms_lookup.keys(),
  File "/tmp/awx_60391_azati6wn/requirements_collections/ansible_collections/netbox/netbox/plugins/inventory/nb_inventory.py", line 305, in get_resource_list_chunked
    largest_value = str(max(query_values))  # values are always id ints
ValueError: max() arg is an empty sequence
```

Full debug logs:
https://gist.github.com/metabsd/8fbd4539f1efdaf0804af856a766d920

**Comment by FragmentedPacket** [comment]
@metabsd I just started looking into this. Do you have any VMs in your NetBox instance? I'm wondering where the empty list of keys is coming from and that would make sense.

Regardless, I will get this fixed, but attempting to try and narrow down the issue so we can add some tests for this.

**Comment by FragmentedPacket** [comment]
This was also discussed on NTC public Slack and appears that the most likely culprit is the lack of VMs defined in NetBox, if @metabsd could validate as well, that would be great!

**Comment by metabsd** [comment]
Yeah, we only have Devices and no VMs for now.

**Comment by DouglasHeriot** [comment]
Ah ok. There's no test case that tests an inventory with no devices, or no vms so that would be why this wasn't caught earlier. I'll think about the best way to test that properly in future. Maybe for now I'll just add some unit tests specifically against `get_resource_list_chunked` with empty inputs.

A workaround until this is fixed - if you set `fetch_all: True`, the `get_resource_list_chunked` method won't be used at all and fetching your 70000 will probably be a lot faster.

**Comment by FragmentedPacket** [comment]
Just submitted a PR for this. If someone can test, that would be great.

@DouglasHeriot Do the unit tests make sense for this? I basically just added a new one to have no `query_values`
