### ISSUE TITLE
netbox_prefix throws with check mode

### ISSUE THREAD

**Issue by lassizci** [netbox-community/ansible_modules#228]
##### ISSUE TYPE

 - Bug Report
 

###### Ansible:

2.9.9

###### Netbox:

2.8.5

###### Collection:

0.2.1

##### SUMMARY

When I run a playbook, that would allocate a new prefix using `netbox_prefix`, the module throws an exception. While the check mode can't universally determine what would it do, it probably shouldn't still throw since it specifies `supports_check_mode=True`

##### STEPS TO REPRODUCE

```yaml
- hosts: netbox
  become: no
  gather_facts: no
  connection: local
  collections:
    - netbox.netbox
  vars:
    netbox_url: https://netbox.smartly.io
    netbox_token: netboxtoken
    my_vrf: test
    prefix_role: foo_prefix

  tasks:
    - name: "ensure prefix exists"
      netbox.netbox.netbox_prefix:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          family: 4
          parent: 192.168.1.0/24
          prefix_length: 26
          vrf: "{{ my_vrf }}"
          description: test
          prefix_role: "{{ prefix_role }}"
        first_available: yes 
        state: present
```

##### EXPECTED RESULTS

Do something else than throw exception.

##### ACTUAL RESULTS

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'prefix'
fatal: [netbox1.smartly.io]: FAILED! => changed=false 
  ansible_facts:
    discovered_interpreter_python: /usr/bin/python3
  module_stderr: |-
    Traceback (most recent call last):
      File "<stdin>", line 102, in <module>
      File "<stdin>", line 94, in _ansiballz_main
      File "<stdin>", line 40, in invoke_module
      File "/usr/lib64/python3.7/runpy.py", line 205, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib64/python3.7/runpy.py", line 96, in _run_module_code
        mod_name, mod_spec, pkg_name, script_name)
      File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_netbox.netbox.netbox_prefix_payload__nu_2rig/ansible_netbox.netbox.netbox_prefix_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_prefix.py", line 295, in <module>
      File "/tmp/ansible_netbox.netbox.netbox_prefix_payload__nu_2rig/ansible_netbox.netbox.netbox_prefix_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_prefix.py", line 291, in main
      File "/tmp/ansible_netbox.netbox.netbox_prefix_payload__nu_2rig/ansible_netbox.netbox.netbox_prefix_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_ipam.py", line 186, in run
      File "/tmp/ansible_netbox.netbox.netbox_prefix_payload__nu_2rig/ansible_netbox.netbox.netbox_prefix_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_ipam.py", line 117, in _get_new_available_prefix
    KeyError: 'prefix'
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```
My use case is I create new prefixes so that when a user creates a PR in github, the playbook is run with `--check` so that it at least some level checks everything works and when the PR is merged, it's run without `--check` so stuff actually gets created.

In practice I have a custom field I use as an identifier, so I can build a list of existing/new prefixes and call `netbox_prefix` in a loop to achieve idempotency, as there probably isn't a universal way to do that otherwise.

As for check mode, maybe it should only throw if there's no space to allocate a new one or something?

**Comment by FragmentedPacket** [comment]
Thanks for reporting this. I will try and get a fix for this taken care of, but not entirely sure when I will have time this week.

**Comment by FragmentedPacket** [comment]
Do you mind testing the attached PR to make sure it resolves the bug on your end?

**Comment by lassizci** [comment]
I can confirm the PR fixes the issue!
