### ISSUE TITLE
netbox_ip_address: get() keywords must be string

### ISSUE THREAD

**Issue by lotusnoir** [netbox-community/ansible_modules#231]
Hello, i dont find how to make work this module netbox_ip_address with a variable on field "interface"

It works when i put  **interface: 1081**

But i get this error when i use a variable
`The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "/usr/lib/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_netbox_ip_address_payload_6xfqpfm9/ansible_netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_ip_address.py", line 305, in <module>
  File "/tmp/ansible_netbox_ip_address_payload_6xfqpfm9/ansible_netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_ip_address.py", line 301, in main
  File "/tmp/ansible_netbox_ip_address_payload_6xfqpfm9/ansible_netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_ipam.py", line 170, in run
  File "/tmp/ansible_netbox_ip_address_payload_6xfqpfm9/ansible_netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 462, in _build_query_params
  File "/tmp/ansible_netbox_ip_address_payload_6xfqpfm9/ansible_netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 432, in _get_query_param_id
  File "/tmp/ansible_netbox_ip_address_payload_6xfqpfm9/ansible_netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 363, in _nb_endpoint_get
TypeError: get() keywords must be strings
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_netbox_ip_address_payload_6xfqpfm9/ansible_netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_ip_address.py\", line 305, in <module>\n  File \"/tmp/ansible_netbox_ip_address_payload_6xfqpfm9/ansible_netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_ip_address.py\", line 301, in main\n  File \"/tmp/ansible_netbox_ip_address_payload_6xfqpfm9/ansible_netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_ipam.py\", line 170, in run\n  File \"/tmp/ansible_netbox_ip_address_payload_6xfqpfm9/ansible_netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py\", line 462, in _build_query_params\n  File \"/tmp/ansible_netbox_ip_address_payload_6xfqpfm9/ansible_netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py\", line 432, in _get_query_param_id\n  File \"/tmp/ansible_netbox_ip_address_payload_6xfqpfm9/ansible_netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py\", line 363, in _nb_endpoint_get\nTypeError: get() keywords must be strings\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}
`

Here is the tasks i'm using in my playbook

```
    - name: Set var vminterfaceid
      set_fact: 
        vminterfaceid: "{{ vm_interface.results | map(attribute='interface.id') | list }}"             
       

    - name: Create netbox_ip_address
      netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          address: "10.1.1.1" 
          interface: "{{ vminterfaceid[0] }}"
        state: present
```
How to make works this module with a variable ?
Thanks in advance

**Comment by FragmentedPacket** [comment]
@lotusnoir What version of Ansible are you on and what version of this collection are you on?

**Comment by lotusnoir** [comment]
hello @FragmentedPacket, thanks for help

ansible version: 2.9.9
python version = 3.6.9
collection: netbox.netbox = 0.2.2

All others modules works properly but this one.

**Comment by FragmentedPacket** [comment]
@lotusnoir Could you test the attached PR and see if this resolves your issue?

**Comment by lotusnoir** [comment]
i just tested and the error disappeared thanks for ur time :+1:
