### ISSUE TITLE
Using remote-host information from "gather_facts" to populate data

### ISSUE THREAD

**Issue by adamwoolhether** [netbox-community/ansible_modules#264]
##### ISSUE TYPE

 - Module question

###### Ansible:

ansible 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

###### Netbox:

v2.8.6
pynetbox (4.3.3)

###### Collection:

v0.2.3
##### SUMMARY

Trying to populate Device Name with the remote host's variable `{{ ansible_hostname }}` results in "netbox", i realize this is due to  `connection: local`, but if i remove the connection setting, an error results.

##### STEPS TO REPRODUCE

```yaml
---
- name: "PLAY: POPULATE NODES"
  hosts: s5d
  remote_user: root
  gather_facts: yes
  collections:
    - netbox.netbox
    
  tasks:
    - name: Debug
      debug: var=ansible_hostname

    - name: "POPULATE S5S Nodes"
      netbox_device:
        netbox_url: https://10.108.5.101/
        netbox_token: XXXX
        validate_certs: no
        data:
          name: "{{ ansible_hostname }}"
          device_type: s5d-mb
          device_role: server-node
          site: rd3-lab-2
          status: active
          rack: Rack 7
          serial: test #"{{ board_serial }}"
          tags: [ 'node', 'child' ]
          comments: test #"{{ bay_loc }}"
```

##### EXPECTED RESULTS

For ansible to create a new device with the host name of the remote host.
##### ACTUAL RESULTS

If `connection: local` is applied, then each device name in Netbox is named "netbox".
Without `connection: local`, an error displays (see below). I've only pasted error for one host below.

```
<10.108.5.108> (0, b'', b'')
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1594262956.0923257-66178-43107508065589/AnsiballZ_netbox_device.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1594262956.0923257-66178-43107508065589/AnsiballZ_netbox_device.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1594262956.0923257-66178-43107508065589/AnsiballZ_netbox_device.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.netbox.netbox.plugins.modules.netbox_device', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_netbox_device_payload_1Mr4wU/ansible_netbox_device_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_device.py", line 300, in <module>
  File "/tmp/ansible_netbox_device_payload_1Mr4wU/ansible_netbox_device_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_device.py", line 290, in main
  File "/tmp/ansible_netbox_device_payload_1Mr4wU/ansible_netbox_device_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 907, in __init__
TypeError: super() takes at least 1 argument (0 given)
fatal: [10.108.5.108]: FAILED! => {
    "changed": false,
    "module_stderr": "Shared connection to 10.108.5.108 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1594262956.0923257-66178-43107508065589/AnsiballZ_netbox_device.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1594262956.0923257-66178-43107508065589/AnsiballZ_netbox_device.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1594262956.0923257-66178-43107508065589/AnsiballZ_netbox_device.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.netbox.netbox.plugins.modules.netbox_device', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\r\n    fname, loader, pkg_name)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\r\n    mod_name, mod_fname, mod_loader, pkg_name)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\r\n    exec code in run_globals\r\n  File \"/tmp/ansible_netbox_device_payload_1Mr4wU/ansible_netbox_device_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_device.py\", line 300, in <module>\r\n  File \"/tmp/ansible_netbox_device_payload_1Mr4wU/ansible_netbox_device_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_device.py\", line 290, in main\r\n  File \"/tmp/ansible_netbox_device_payload_1Mr4wU/ansible_netbox_device_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py\", line 907, in __init__\r\nTypeError: super() takes at least 1 argument (0 given)\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```

**Comment by FragmentedPacket** [comment]
Looking at the moment appears to be executing the modules with Python2, which is not supported, but not sure if that is your only issue at this point.

You can always set `ansible_python_interpreter` in `group_vars/all` or just as a var within the playbook to your Python3 installation.

**Comment by FragmentedPacket** [comment]
After looking at this, you can add `connection: local` to the `netbox_device` task and that should work as well, I believe.

**Comment by adamwoolhether** [comment]
I notice there is an issue using any remote-defined variable to populate data.

For example: if I register a custom variable to define the bay location:
```
    - name: "DEFINE LOCATION IN CHASSIS"
      shell: dmidecode -t 2 | grep -i location | cut -d ' ' -f 4
      register: bay_loc
```
i cannot use it to, say, populate comments data
```yml
        data:
          name: "{{ ansible_inventory }}"
...
          comments: "{{ bay_loc.stdout }}"
```

Of course, with `connection: local` this isn't a problem, but the data wouldn't be incorrect as it isn't coming from the remote host.

**Comment by adamwoolhether** [comment]
> Looking at the moment appears to be executing the modules with Python2, which is not supported, but not sure if that is your only issue at this point.
> 
> You can always set `ansible_python_interpreter` in `group_vars/all` or just as a var within the playbook to your Python3 installation.

Would this mean each remote hots also needs the pynetbox module/collections installed? Results in error
```
"msg": "Failed to import the required Python library (pynetbox) on s5d03's Python /usr/bin/python3.
```

**Comment by adamwoolhether** [comment]
> After looking at this, you can add `connection: local` to the `netbox_device` task and that should work as well, I believe.

This states i
```
"msg": "Unsupported parameters for (netbox_device) module: connection Supported parameters include: data, netbox_token, netbox_url, query_params, state, validate_certs"}
```

> After looking at this, you can add `connection: local` to the `netbox_device` task and that should work as well, I believe.

Hey, this fixed it! Thank you so much. Really sorry to be bothering you great people so much.
