### ISSUE TITLE
Failed to parse inventory.yml with auto plugin: Invalid group name supplied, expected a string but got <class 'dict'>

### ISSUE THREAD

**Issue by MaartenMol** [netbox-community/ansible_modules#338]
##### ISSUE TYPE

 - Bug Report

###### Ansible:

2.9.11

###### Netbox:

2.9.3

###### Collection:

1.0.2

##### SUMMARY

Can't sync inventory from netbox: (I think because of a change in Netbox 2.9?)

```
[WARNING]:  * Failed to parse /tmp/awx_786_4n4fkne9/project/inventory.yml with
auto plugin: Invalid group name supplied, expected a string but got <class
'dict'> for {'id': 2, 'url': 'http://netbox/api/extras/tags/2/',
'name': 'PrimaryDomainController', 'slug': 'primarydomaincontroller', 'color':
'9e9e9e'}
```

##### STEPS TO REPRODUCE

```yaml
plugin: netbox.netbox.nb_inventory
config_context: true
interfaces: true
flatten_custom_fields: true
group_names_raw: true
group_by:
  - tags
query_filters:
  - tenant: test128
  - tag: vm
```

##### EXPECTED RESULTS

To sync the inventory but got an error.

##### ACTUAL RESULTS

```
    2.262 INFO     Updating inventory 12: Klant - TestKlant128
    2.771 DEBUG    Using base command: python /usr/bin/ansible-inventory -i /tmp/awx_786_4n4fkne9/project/inventory.yml --playbook-dir /tmp/awx_786_4n4fkne9/project -vvvvv
    2.771 INFO     Reading Ansible inventory source: /tmp/awx_786_4n4fkne9/project/inventory.yml
    2.774 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible
    2.774 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/usr/pgsql-10/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    2.774 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python3.6/site-packages:
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py", line 154, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1149, in handle
    raise exc
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1039, in handle
    venv_path=venv_path, verbosity=self.verbosity).load()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 215, in load
    return self.command_to_json(base_args + ['--list'])
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 198, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:
stderr:
ansible-inventory 2.9.11
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-inventory
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /tmp/awx_786_4n4fkne9/project/inventory.yml as it did not pass its verify_file() method
script declined parsing /tmp/awx_786_4n4fkne9/project/inventory.yml as it did not pass its verify_file() method
Fetching: https://netbox/api/docs/?format=openapi
Fetching: https://netbox/api/dcim/devices/?limit=0&tenant=testklant128&tag=vm
Fetching: https://netbox/api/virtualization/virtual-machines/?limit=0&tenant=testklant128&tag=vm
Fetching: https://netbox/api/dcim/sites/?limit=0
Fetching: https://netbox/api/dcim/regions/?limit=0
Fetching: https://netbox/api/tenancy/tenants/?limit=0
Fetching: https://netbox/api/dcim/racks/?limit=0
Fetching: https://netbox/api/dcim/rack-groups/?limit=0
Fetching: https://netbox/api/dcim/device-roles/?limit=0
Fetching: https://netbox/api/dcim/platforms/?limit=0
Fetching: https://netbox/api/dcim/device-types/?limit=0
Fetching: https://netbox/api/dcim/manufacturers/?limit=0
Fetching: https://netbox/api/virtualization/clusters/?limit=0
Fetching: https://netbox/api/dcim/interfaces/?limit=0
Fetching: https://netbox/api/ipam/services/?limit=0
Fetching: https://netbox/api/virtualization/interfaces/?limit=0
Fetching: https://netbox/api/ipam/ip-addresses/?limit=0&assigned_to_interface=true
toml declined parsing /tmp/awx_786_4n4fkne9/project/inventory.yml as it did not pass its verify_file() method
[WARNING]:  * Failed to parse /tmp/awx_786_4n4fkne9/project/inventory.yml with
auto plugin: Invalid group name supplied, expected a string but got <class
'dict'> for {'id': 2, 'url': 'http://netbox/api/extras/tags/2/',
'name': 'PrimaryDomainController', 'slug': 'primarydomaincontroller', 'color':
'9e9e9e'}
  File "/usr/lib/python3.6/site-packages/ansible/inventory/manager.py", line 280, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/auto.py", line 58, in parse
    plugin.parse(inventory, loader, path, cache=cache)
  File "/var/lib/awx/.ansible/collections/ansible_collections/netbox/netbox/plugins/inventory/nb_inventory.py", line 1383, in parse
    self.main()
  File "/var/lib/awx/.ansible/collections/ansible_collections/netbox/netbox/plugins/inventory/nb_inventory.py", line 1342, in main
    self.add_host_to_groups(host=host, hostname=hostname)
  File "/var/lib/awx/.ansible/collections/ansible_collections/netbox/netbox/plugins/inventory/nb_inventory.py", line 1191, in add_host_to_groups
    transformed_group_name = self.inventory.add_group(group=group_name)
  File "/usr/lib/python3.6/site-packages/ansible/inventory/data.py", line 163, in add_group
    raise AnsibleError("Invalid group name supplied, expected a string but got %s for %s" % (type(group), group))
[WARNING]:  * Failed to parse /tmp/awx_786_4n4fkne9/project/inventory.yml with
yaml plugin: Plugin configuration YAML file, not YAML inventory
  File "/usr/lib/python3.6/site-packages/ansible/inventory/manager.py", line 280, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/yaml.py", line 112, in parse
    raise AnsibleParserError('Plugin configuration YAML file, not YAML inventory')
[WARNING]:  * Failed to parse /tmp/awx_786_4n4fkne9/project/inventory.yml with
ini plugin: Invalid host pattern 'plugin:' supplied, ending in ':' is not
allowed, this character is reserved to provide a port.
  File "/usr/lib/python3.6/site-packages/ansible/inventory/manager.py", line 280, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/ini.py", line 138, in parse
    raise AnsibleParserError(e)
[WARNING]: Unable to parse /tmp/awx_786_4n4fkne9/project/inventory.yml as an
inventory source
ERROR! No inventory was parsed, please check your configuration and options.

```

**Comment by paulmcgoldrick** [comment]
Had this same issue, Looks like it is covered in #287

**Comment by FragmentedPacket** [comment]
Closing this as duplicate, but fix should be merged in soon.
