### ISSUE TITLE
Can't update tags due to changes in Netbox 2.9 

### ISSUE THREAD

**Issue by autogun** [netbox-community/ansible_modules#348]
##### ISSUE TYPE

 - Bug Report

###### Ansible:
```
ansible --version
ansible 2.9.9
  config file = /home/danny/test/ansible.cfg
  configured module search path = ['/home/danny/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/python38/lib/python3.8/site-packages/ansible
  executable location = /opt/python38/bin/ansible
  python version = 3.8.3 (default, May 25 2020, 00:36:17) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

###### Netbox:
`v2.9.4`

###### Collection:
`netbox:1.0.2`

###### Pynetbox:
`5.1.0`

##### SUMMARY
Changes to Tag Creation ([#3703](https://github.com/netbox-community/netbox/issues/3703)) broke `tags` usage for supported  modules.

##### STEPS TO REPRODUCE

1. Create a tag first
2. Try below code with Netbox `v2.9.4`
```yaml
- name: "VIRTUAL MACHINE"
  local_action:
    module: netbox_virtual_machine
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ setup.ansible_facts.ansible_fqdn }}"
      status: Active
      virtual_machine_role: "Virtual Machine"
      tags:
        - test
```

##### EXPECTED RESULTS

Tag should be added to the virtual machine.

##### ACTUAL RESULTS

```
The error was: pynetbox.core.query.RequestError: The request failed with code 400 Bad Request: {'tags': [['Related objects must be referenced by numeric ID or by dictionary of attributes. Received an unrecognized value: test']}
```

```
TASK [VIRTUAL MACHINE] *************************************************************************************************************************************************************************************************
task path: /home/danny/test.yml:13
Using module file /home/danny/.ansible/collections/ansible_collections/netbox/netbox/plugins/modules/netbox_virtual_machine.py
Pipelining is enabled.
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: danny
<localhost> EXEC /bin/sh -c '/opt/python38/bin/python3.8 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "/opt/python38/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/opt/python38/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/python38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_netbox_virtual_machine_payload_k9mc8m3a/ansible_netbox_virtual_machine_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_virtual_machine.py", line 248, in <module>
  File "/tmp/ansible_netbox_virtual_machine_payload_k9mc8m3a/ansible_netbox_virtual_machine_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_virtual_machine.py", line 244, in main
  File "/tmp/ansible_netbox_virtual_machine_payload_k9mc8m3a/ansible_netbox_virtual_machine_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_virtualization.py", line 69, in run
  File "/tmp/ansible_netbox_virtual_machine_payload_k9mc8m3a/ansible_netbox_virtual_machine_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 939, in _ensure_object_exists
  File "/tmp/ansible_netbox_virtual_machine_payload_k9mc8m3a/ansible_netbox_virtual_machine_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 918, in _update_netbox_object
  File "/opt/python38/lib/python3.8/site-packages/pynetbox/core/response.py", line 419, in update
    return self.save()
  File "/opt/python38/lib/python3.8/site-packages/pynetbox/core/response.py", line 391, in save
    if req.patch({i: serialized[i] for i in diff}):
  File "/opt/python38/lib/python3.8/site-packages/pynetbox/core/query.py", line 409, in patch
    return self._make_call(verb="patch", data=data)
  File "/opt/python38/lib/python3.8/site-packages/pynetbox/core/query.py", line 274, in _make_call
    raise RequestError(req)
pynetbox.core.query.RequestError: The request failed with code 400 Bad Request: {'tags': [['Related objects must be referenced by numeric ID or by dictionary of attributes. Received an unrecognized value: test']]}
fatal: [test01 -> localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/opt/python38/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/opt/python38/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/opt/python38/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_netbox_virtual_machine_payload_k9mc8m3a/ansible_netbox_virtual_machine_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_virtual_machine.py\", line 248, in <module>\n  File \"/tmp/ansible_netbox_virtual_machine_payload_k9mc8m3a/ansible_netbox_virtual_machine_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_virtual_machine.py\", line 244, in main\n  File \"/tmp/ansible_netbox_virtual_machine_payload_k9mc8m3a/ansible_netbox_virtual_machine_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_virtualization.py\", line 69, in run\n  File \"/tmp/ansible_netbox_virtual_machine_payload_k9mc8m3a/ansible_netbox_virtual_machine_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py\", line 939, in _ensure_object_exists\n  File \"/tmp/ansible_netbox_virtual_machine_payload_k9mc8m3a/ansible_netbox_virtual_machine_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py\", line 918, in _update_netbox_object\n  File \"/opt/python38/lib/python3.8/site-packages/pynetbox/core/response.py\", line 419, in update\n    return self.save()\n  File \"/opt/python38/lib/python3.8/site-packages/pynetbox/core/response.py\", line 391, in save\n    if req.patch({i: serialized[i] for i in diff}):\n  File \"/opt/python38/lib/python3.8/site-packages/pynetbox/core/query.py\", line 409, in patch\n    return self._make_call(verb=\"patch\", data=data)\n  File \"/opt/python38/lib/python3.8/site-packages/pynetbox/core/query.py\", line 274, in _make_call\n    raise RequestError(req)\npynetbox.core.query.RequestError: The request failed with code 400 Bad Request: {'tags': [['Related objects must be referenced by numeric ID or by dictionary of attributes. Received an unrecognized value: test']]}\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by FragmentedPacket** [comment]
Thanks for the heads up. I will get this updated to work with it. It is going to change the way tags are defined as they will need to be dictionaries.

**Comment by fouram** [comment]
This has also broken the inventory plugin, which throws this:

```
`[WARNING]:  * Failed to parse /home/user/netbox_inventory.yml with auto plugin: sequence item 1: expected string or Unicode, dict found
  File "/usr/lib/python2.7/dist-packages/ansible/inventory/manager.py", line 280, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/inventory/auto.py", line 58, in parse
    plugin.parse(inventory, loader, path, cache=cache)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/inventory/netbox.py", line 465, in parse
    self.main()
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/inventory/netbox.py", line 443, in main
    self.add_host_to_groups(host=host, hostname=hostname)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/inventory/netbox.py", line 404, in add_host_to_groups
    group_name = "_".join([group, `sub_group])`

Do you want a separate issue opened for this? It seems support for tags across all parts of this is now broken with the new way they're being returned from netbox.

**Comment by FragmentedPacket** [comment]
@fouram that issue should be fixed in develop

**Comment by FragmentedPacket** [comment]
@autogun This should be fixed in `devel` now.

I'm going to try and get in a few other issues and then cut a new release (v1.0.3). I hope to do that within the next few days.
