### ISSUE TITLE
Issues with netbox_device and netbox_virtual_machine modeuls after upgrading netbox to 2.10

### ISSUE THREAD

**Issue by Hitman247m** [netbox-community/ansible_modules#393]
I upgraded my netbox instance to 2.10 yesterday, and it seems like it broke these two modules:

- `netbox.netbox.netbox_device`
- `netbox.netbox.netbox_virtual_machine`

Software Versions:
- Netbox: `2.10.0`
- Ansible: `2.10.3`
- Python: `3.9.1`
- Netbox Galaxy Collection: `1.1.0`
- pynetbox: `5.1.1`

Here is an example of the error message: 
```YAML
TASK [Netbox-Create_VM : Create VM] ************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: pynetbox.core.query.RequestError: The request failed with code 500 Internal Server Error: {'error': 'Expected view VirtualMachineViewSet to be called with a URL keyword argument named "pk". Fix your URL conf, or set the `.lookup_field` attribute on the view correctly.', 'exception': 'AssertionError', 'netbox_version': '2.10.0', 'python_version': '3.9.1'}
fatal: [host.example.com]: FAILED! => changed=false
  module_stderr: |-
    Traceback (most recent call last):
      File "/Users/username/.ansible/tmp/ansible-tmp-1608132940.7761931-76792-204102650777528/AnsiballZ_netbox_virtual_machine.py", line 102, in <module>
        _ansiballz_main()
      File "/Users/username/.ansible/tmp/ansible-tmp-1608132940.7761931-76792-204102650777528/AnsiballZ_netbox_virtual_machine.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/Users/username/.ansible/tmp/ansible-tmp-1608132940.7761931-76792-204102650777528/AnsiballZ_netbox_virtual_machine.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.netbox.netbox.plugins.modules.netbox_virtual_machine', init_globals=None, run_name='__main__', alter_sys=True)
      File "/usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 210, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/var/folders/z0/bmldr3nj1px1739qcwq7k58w0000gn/T/ansible_netbox.netbox.netbox_virtual_machine_payload_f8c2m5u2/ansible_netbox.netbox.netbox_virtual_machine_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_virtual_machine.py", line 249, in <module>
      File "/var/folders/z0/bmldr3nj1px1739qcwq7k58w0000gn/T/ansible_netbox.netbox.netbox_virtual_machine_payload_f8c2m5u2/ansible_netbox.netbox.netbox_virtual_machine_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_virtual_machine.py", line 244, in main
      File "/var/folders/z0/bmldr3nj1px1739qcwq7k58w0000gn/T/ansible_netbox.netbox.netbox_virtual_machine_payload_f8c2m5u2/ansible_netbox.netbox.netbox_virtual_machine_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_virtualization.py", line 24, in __init__
      File "/var/folders/z0/bmldr3nj1px1739qcwq7k58w0000gn/T/ansible_netbox.netbox.netbox_virtual_machine_payload_f8c2m5u2/ansible_netbox.netbox.netbox_virtual_machine_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 464, in __init__
      File "/var/folders/z0/bmldr3nj1px1739qcwq7k58w0000gn/T/ansible_netbox.netbox.netbox_virtual_machine_payload_f8c2m5u2/ansible_netbox.netbox.netbox_virtual_machine_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 742, in _change_choices_id
      File "/var/folders/z0/bmldr3nj1px1739qcwq7k58w0000gn/T/ansible_netbox.netbox.netbox_virtual_machine_payload_f8c2m5u2/ansible_netbox.netbox.netbox_virtual_machine_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 712, in _fetch_choice_value
      File "/usr/local/lib/python3.9/site-packages/pynetbox/core/endpoint.py", line 319, in choices
        req = Request(
      File "/usr/local/lib/python3.9/site-packages/pynetbox/core/query.py", line 421, in options
        return self._make_call(verb="options")
      File "/usr/local/lib/python3.9/site-packages/pynetbox/core/query.py", line 274, in _make_call
        raise RequestError(req)
    pynetbox.core.query.RequestError: The request failed with code 500 Internal Server Error: {'error': 'Expected view VirtualMachineViewSet to be called with a URL keyword argument named "pk". Fix your URL conf, or set the `.lookup_field` attribute on the view correctly.', 'exception': 'AssertionError', 'netbox_version': '2.10.0', 'python_version': '3.9.1'}
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
	to retry, use: --limit @/Users/username/ansible/retry-files/pb-Netbox.retry
```

**Comment by FragmentedPacket** [comment]
This should be fixed with Ansible 2.10.1.

Issue: https://github.com/netbox-community/netbox/issues/5470
