### ISSUE TITLE
`AttributeError: 'dict' object has no attribute 'serialize'` 

### ISSUE THREAD

**Issue by syedahaider97** [netbox-community/ansible_modules#457]
##### ISSUE TYPE
 - Bug Report

###### Ansible:

`ansible 2.10.6`

###### Netbox:

`2.6.8`

###### pynetbox:

`pynetbox (5.3.1)`

###### Collection:

`netbox.netbox     2.0.0`

##### SUMMARY

We were upgrading ansible and its corresponding collection code to from 2.9 to 2.10. Doing so however, broke much of our previously functioning netbox operations.

##### STEPS TO REPRODUCE

When running the following code excerpt to obtain a new IP address from netbox, 

```
- name: provision | allocate guest IP addresses
  netbox.netbox.netbox_ip_address:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_api_token }}"
    data:
      prefix: "{{ subnet_address }}"
      tags: ["ansible", "{{ guest_type }}" , "{{ inventory_hostname }}", "{{ user }}", "{{ network_type }}"]
      description: "{{ inventory_hostname }}-{{ user }}"
      status: active
    state: new
    # validate_certs: no
  register: netbox_ips
```

we are immediately presented with the following error:

```
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1614871429.7014062-113537-268987801420289/AnsiballZ_netbox_ip_address.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1614871429.7014062-113537-268987801420289/AnsiballZ_netbox_ip_address.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1614871429.7014062-113537-268987801420289/AnsiballZ_netbox_ip_address.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.netbox.netbox.plugins.modules.netbox_ip_address', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_netbox.netbox.netbox_ip_address_payload_1o_idjn8/ansible_netbox.netbox.netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_ip_address.py", line 384, in <module>
  File "/tmp/ansible_netbox.netbox.netbox_ip_address_payload_1o_idjn8/ansible_netbox.netbox.netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_ip_address.py", line 380, in main
  File "/tmp/ansible_netbox.netbox.netbox_ip_address_payload_1o_idjn8/ansible_netbox.netbox.netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_ipam.py", line 204, in run
  File "/tmp/ansible_netbox.netbox.netbox_ip_address_payload_1o_idjn8/ansible_netbox.netbox.netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_ipam.py", line 52, in _handle_state_new_present
  File "/tmp/ansible_netbox.netbox.netbox_ip_address_payload_1o_idjn8/ansible_netbox.netbox.netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_ipam.py", line 105, in _get_new_available_ip_address
AttributeError: 'dict' object has no attribute 'serialize'
failed: [zt93ke] (item=1) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": 1,
    "module_stderr": "Shared connection to 10.xx.xx.xx closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1614871429.7014062-113537-268987801420289/AnsiballZ_netbox_ip_address.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1614871429.7014062-113537-268987801420289/AnsiballZ_netbox_ip_address.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1614871429.7014062-113537-268987801420289/AnsiballZ_netbox_ip_address.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.netbox.netbox.plugins.modules.netbox_ip_address', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_netbox.netbox.netbox_ip_address_payload_1o_idjn8/ansible_netbox.netbox.netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_ip_address.py\", line 384, in <module>\r\n  File \"/tmp/ansible_netbox.netbox.netbox_ip_address_payload_1o_idjn8/ansible_netbox.netbox.netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_ip_address.py\", line 380, in main\r\n  File \"/tmp/ansible_netbox.netbox.netbox_ip_address_payload_1o_idjn8/ansible_netbox.netbox.netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_ipam.py\", line 204, in run\r\n  File \"/tmp/ansible_netbox.netbox.netbox_ip_address_payload_1o_idjn8/ansible_netbox.netbox.netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_ipam.py\", line 52, in _handle_state_new_present\r\n  File \"/tmp/ansible_netbox.netbox.netbox_ip_address_payload_1o_idjn8/ansible_netbox.netbox.netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_ipam.py\", line 105, in _get_new_available_ip_address\r\nAttributeError: 'dict' object has no attribute 'serialize'\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

##### EXPECTED RESULTS

A returned IP Address

##### ACTUAL RESULTS

The error above

**Comment by syedahaider97** [comment]
Thanks for the pointer, the target host we were running it on has pynetbox at version 4.3.1 . Our controle node was the one running 5.3.1, but I see now that it doesn't make a difference.

Upgrading the target to 5.3.1 fixed the issue!

**Comment by FragmentedPacket** [comment]
Great to hear! Let me know if you encounter any other issues!
