### ISSUE TITLE
nb_inventory not syncing in Ansible tower

### ISSUE THREAD

**Issue by parsnep** [netbox-community/ansible_modules#459]
We can no longer sync our netbox inventory to Ansible tower using the nb_inventory plugin.
It worked with the same config before we upgraded tower from 3.7.3 to 3.8.1.
Our Netbox token is included in tower with a custom credential, using the env netbox_token.

**Versions:**
Ansible tower version: 3.8.1
Ansible version: Ansible 2.9.17
Netbox.netbox verions: 2.1.0
Netbox version: v2.10.5

**Our Inventory play now:**
 ```
plugin: netbox.netbox.nb_inventory
api_endpoint: https://url
validate_certs: True
config_context: True
interfaces: False
group_by:
  - device_roles
  - tags
query_filters:
  - role: csr
device_query_filters:
  - has_primary_ip: True
timeout: 600
```

**Erorr:**
```
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==3.8.1', 'console_scripts', 'awx-manage')()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/__init__.py", line 154, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1142, in handle
    raise exc
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1032, in handle
    venv_path=venv_path, verbosity=self.verbosity).load()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 208, in load
    return self.command_to_json(base_args + ['--list'])
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 191, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:
stderr:
[WARNING]:  * Failed to parse
/tmp/awx_29502_ax1xlg3v/project/netbox_inventory.yml with auto plugin: No
module named
'ansible_collections.ansible.netcommon.plugins.module_utils.compat'
[WARNING]:  * Failed to parse
/tmp/awx_29502_ax1xlg3v/project/netbox_inventory.yml with yaml plugin: Plugin
configuration YAML file, not YAML inventory
[WARNING]:  * Failed to parse
/tmp/awx_29502_ax1xlg3v/project/netbox_inventory.yml with ini plugin: Invalid
host pattern '---' supplied, '---' is normally a sign this is a YAML file.
[WARNING]: Unable to parse /tmp/awx_29502_ax1xlg3v/project/netbox_inventory.yml
as an inventory source
ERROR! No inventory was parsed, please check your configuration and options.
```

**Comment by parsnep** [comment]
It seems if i run it with ansible.netcommon version 1.5.0, it works.

**Comment by hyudra** [comment]
I also got the same problem,

how to change netcommon on tower?

**Comment by parsnep** [comment]
In youre requirements file you can specify the version:
```
---
collections:
- name: ansible.netcommon
  version: 1.5.0
```

**Comment by cremsburg** [comment]
Just here to echo, all of my inventory stopped syncing over the weekend. Inserting the `ansible.netcommon` into my collections fixed the issue

```
collections:
  - name: ansible.netcommon
    version: 1.5.0
  - name: netbox.netbox
    version: 2.1.0
```

**Comment by cremsburg** [comment]
adding logs for funtime
![image](https://user-images.githubusercontent.com/76797306/110336227-457fa480-7fea-11eb-8c1a-93e808b4255a.png)

**Comment by FragmentedPacket** [comment]
Thanks guys! Fix is in develop and I'll cut a new release tonight. Sorry for the breaking dependency due to lack of proper pinning!

**Comment by cremsburg** [comment]
@FragmentedPacket is there something we could have done within our environment to account for this? I had the collection pinned to version 2.0.0 but was still affected

**Comment by FragmentedPacket** [comment]
I don't think so. We removed that dependency from the collection, but it was on the netbox collection's end. They removed their ipaddress compat utils in favor of just the regular ipaddress standard lib.

**Comment by FragmentedPacket** [comment]
Release v3.0.0 so upgrade and it should work. All dependencies are now removed.
