### ISSUE TITLE
Update of a lag in netbox_device_interface fails

### ISSUE THREAD

**Issue by misch42** [netbox-community/ansible_modules#517]
```
  - name: Create interface within Netbox with only required information
    netbox.netbox.netbox_device_interface:
      netbox_url: http://127.0.0.1:8001
      netbox_token: 12345
      data:
        device: switch07
        name: GigabitEthernet1
      state: present
    delegate_to: localhost
```

creates a new interface for the given device. But a subsequent 

```
   - name: Create interface within Netbox with only required information
    netbox.netbox.netbox_device_interface:
      netbox_url: http://127.0.0.1:8001
      netbox_token: 12345
      data:
        device: switch07
        name: GigabitEthernet1
        lag:
          name: Port-channel1
      state: present
    delegate_to: localhost
```

fails with

```
The full traceback is:
Traceback (most recent call last):
  File "/home/misch/.ansible/tmp/ansible-tmp-1621104979.8126645-19899-267769929080845/AnsiballZ_netbox_device_interface.py", line 102, in <module>
    _ansiballz_main()
  File "/home/misch/.ansible/tmp/ansible-tmp-1621104979.8126645-19899-267769929080845/AnsiballZ_netbox_device_interface.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/misch/.ansible/tmp/ansible-tmp-1621104979.8126645-19899-267769929080845/AnsiballZ_netbox_device_interface.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.netbox.netbox.plugins.modules.netbox_device_interface', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_netbox.netbox.netbox_device_interface_payload_u3cko4r2/ansible_netbox.netbox.netbox_device_interface_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_device_interface.py", line 326, in <module>                                                                                                              
  File "/tmp/ansible_netbox.netbox.netbox_device_interface_payload_u3cko4r2/ansible_netbox.netbox.netbox_device_interface_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_device_interface.py", line 322, in main                                                                                                                  
  File "/tmp/ansible_netbox.netbox.netbox_device_interface_payload_u3cko4r2/ansible_netbox.netbox.netbox_device_interface_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_dcim.py", line 180, in run                                                                                                                          
  File "/tmp/ansible_netbox.netbox.netbox_device_interface_payload_u3cko4r2/ansible_netbox.netbox.netbox_device_interface_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 1110, in _ensure_object_exists                                                                                                      
  File "/tmp/ansible_netbox.netbox.netbox_device_interface_payload_u3cko4r2/ansible_netbox.netbox.netbox_device_interface_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 1089, in _update_netbox_object                                                                                                      
  File "/usr/local/lib/python3.6/site-packages/pynetbox/core/response.py", line 419, in update
    return self.save()
  File "/usr/local/lib/python3.6/site-packages/pynetbox/core/response.py", line 391, in save
    if req.patch({i: serialized[i] for i in diff}):
  File "/usr/local/lib/python3.6/site-packages/pynetbox/core/query.py", line 409, in patch
    return self._make_call(verb="patch", data=data)
  File "/usr/local/lib/python3.6/site-packages/pynetbox/core/query.py", line 274, in _make_call
    raise RequestError(req)
pynetbox.core.query.RequestError: The request failed with code 400 Bad Request: {'non_field_errors': ['Expected a list of items but got type "dict".']}
fatal: [switch07]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/misch/.ansible/tmp/ansible-tmp-1621104979.8126645-19899-267769929080845/AnsiballZ_netbox_device_interface.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/misch/.ansible/tmp/ansible-tmp-1621104979.8126645-19899-267769929080845/AnsiballZ_netbox_device_interface.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/misch/.ansible/tmp/ansible-tmp-1621104979.8126645-19899-267769929080845/AnsiballZ_netbox_device_interface.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.netbox.netbox.plugins.modules.netbox_device_interface', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_netbox.netbox.netbox_device_interface_payload_u3cko4r2/ansible_netbox.netbox.netbox_device_interface_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_device_interface.py\", line 326, in <module>\n  File \"/tmp/ansible_netbox.netbox.netbox_device_interface_payload_u3cko4r2/ansible_netbox.netbox.netbox_device_interface_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_device_interface.py\", line 322, in main\n  File \"/tmp/ansible_netbox.netbox.netbox_device_interface_payload_u3cko4r2/ansible_netbox.netbox.netbox_device_interface_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_dcim.py\", line 180, in run\n  File \"/tmp/ansible_netbox.netbox.netbox_device_interface_payload_u3cko4r2/ansible_netbox.netbox.netbox_device_interface_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py\", line 1110, in _ensure_object_exists\n  File \"/tmp/ansible_netbox.netbox.netbox_device_interface_payload_u3cko4r2/ansible_netbox.netbox.netbox_device_interface_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py\", line 1089, in _update_netbox_object\n  File \"/usr/local/lib/python3.6/site-packages/pynetbox/core/response.py\", line 419, in update\n    return self.save()\n  File \"/usr/local/lib/python3.6/site-packages/pynetbox/core/response.py\", line 391, in save\n    if req.patch({i: serialized[i] for i in diff}):\n  File \"/usr/local/lib/python3.6/site-packages/pynetbox/core/query.py\", line 409, in patch\n    return self._make_call(verb=\"patch\", data=data)\n  File \"/usr/local/lib/python3.6/site-packages/pynetbox/core/query.py\", line 274, in _make_call\n    raise RequestError(req)\npynetbox.core.query.RequestError: The request failed with code 400 Bad Request: {'non_field_errors': ['Expected a list of items but got type \"dict\".']}\n",                                                                                      
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

For comparison that second playbook including the LAG data works if the interface does not exist already.

**Comment by rodvand** [comment]
@misch42 Is this still an issue? I am unable to reproduce it with the data in the issue.
