### ISSUE TITLE
ansible-inventory fails due to 404 error from /api/dcim/rack-groups/?limit=0

### ISSUE THREAD

**Issue by S0LERA** [netbox-community/ansible_modules#520]
##### ISSUE TYPE

 - Bug Report

##### SUMMARY

Ansible inventory with netbox inventory plugin returns no hosts due to a 404 HTTP error produced in path /api/dcim/rack-groups/?limit=0

##### STEPS TO REPRODUCE

Obtain ansible inventory from netbox api

```yaml
ansible-inventory --graph
```

##### EXPECTED RESULTS

Ansible return a list with the hosts in netbox.

##### ACTUAL RESULTS

No inventory returned due to exception

This is the inventory file:

```
plugin: netbox.netbox.nb_inventory
api_endpoint: NETBOX_IP
token: TOKEN
```

First of all, I exec the command and this was the return:

```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/home/rundeck/.ansible/collections/ansible_collections/netbox/netbox/plugins/inventory/nb_inventory.py", line 297, in _fetch_information
    follow_redirects=self.follow_redirects,
  File "/usr/local/lib/python3.6/dist-packages/ansible/module_utils/urls.py", line 1399, in open_url
    unredirected_headers=unredirected_headers)
  File "/usr/local/lib/python3.6/dist-packages/ansible/module_utils/urls.py", line 1304, in open
    return urllib_request.urlopen(request, None, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

```

Then, I edited the file nb_inventory.py to debug the problem and print all the urls requested by the script to netbox api. And, all the urls returned ok except the one of /api/dcim/rack-groups/?limit=0 that not exists. I tried to access this url from the navigator and returns the same 404 error.

So, I commented the script line that calls for that url (self.refresh_rack_groups_lookup) and the ansible-inventory --graph command works, returning the inventory.

**Comment by FragmentedPacket** [comment]
You'll want to use at least `3.1.0` of the collection to get past the error, but I need to cut a new release to have it actually work when grouping by `location` which I can try and do today.

**Comment by S0LERA** [comment]
Thanks, I will wait for the new release before update the version.

**Comment by FragmentedPacket** [comment]
3.1.1 has been released. I'm going to close this issue, but please re-open if you still have issues with the latest version.
