### ISSUE TITLE
netbox_ip_address fails to check for existing IP address if interface already has an IP assigned

### ISSUE THREAD

**Issue by JerradGit** [netbox-community/ansible_modules#555]
##### ISSUE TYPE
 - Bug Report
###### Ansible:
ansible 2.10.11
  config file = /home/tmp/files/ansible/ansible.cfg
  configured module search path = ['/home/tmp/files/ansible/library']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, May  6 2021, 00:05:59) [GCC 10.2.1 20201203]

###### Netbox:
2.11.7

###### Collection:
netbox.netbox         3.1.1

###### pynetbox:
pynetbox                       6.1.2

##### SUMMARY
When method _ensure_ip_in_prefix_present_on_netif in the netbox_ipam.py module attempts to retrieve the last IP address object under a given parent prefix and interface, it fails since pynetbox returns a generator object instead of a list.  If the interface has no IP address assigned yet, the playbook will execute, however when re-executing the playbook it will fail.

https://github.com/netbox-community/ansible_modules/blob/94163307fa7fe981d4c835cc1e48b07c9d20b84d/plugins/module_utils/netbox_ipam.py#L84

In order to retrieve the last IP object the attached_ips needs to be converted to a list or we need to iterate over the generator until we obtain the last item.

I made a few attempts to fix this locally which work, but not sure of the most pythonic approach to take with this
```
        if attached_ips:  
            self.nb_object = list(attached_ips)[-1].serialize()
```

```
        if attached_ips:  
            self.nb_object = max(enumerate(attached_ips))[1].serialize()
```

##### STEPS TO REPRODUCE
Attempt to assign an IP address to a device interface which belongs to a given prefix, once it assigns the IP address re-execute the play

```
- name: Ensure that the server IPMI has an IP address in the IPMI prefix
  netbox.netbox.netbox_ip_address:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      prefix: 10.232.188.128/26
      assigned_object:
        name: IPMI
        device: SERVER-1
    state: present
```
##### EXPECTED RESULTS
Expected the play to succeed since the interface currently has an IP address assigned in the defined parent prefix

##### ACTUAL RESULTS
```
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1624643880.8584547-30710-199568632089406/AnsiballZ_netbox_ip_address.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1624643880.8584547-30710-199568632089406/AnsiballZ_netbox_ip_address.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1624643880.8584547-30710-199568632089406/AnsiballZ_netbox_ip_address.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.netbox.netbox.plugins.modules.netbox_ip_address', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_netbox.netbox.netbox_ip_address_payload_i5g5k7ds/ansible_netbox.netbox.netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_ip_address.py", line 384, in <module>
  File "/tmp/ansible_netbox.netbox.netbox_ip_address_payload_i5g5k7ds/ansible_netbox.netbox.netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_ip_address.py", line 380, in main
  File "/tmp/ansible_netbox.netbox.netbox_ip_address_payload_i5g5k7ds/ansible_netbox.netbox.netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_ipam.py", line 206, in run
  File "/tmp/ansible_netbox.netbox.netbox_ip_address_payload_i5g5k7ds/ansible_netbox.netbox.netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_ipam.py", line 48, in _handle_state_new_present
  File "/tmp/ansible_netbox.netbox.netbox_ip_address_payload_i5g5k7ds/ansible_netbox.netbox.netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_ipam.py", line 84, in _ensure_ip_in_prefix_present_on_netif
TypeError: 'RecordSet' object is not subscriptable
fatal: [SERVER-1]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "/root/.ansible/tmp/ansible-tmp-1624643880.8584547-30710-199568632089406/AnsiballZ_netbox_ip_address.py", line 102, in <module>
        _ansiballz_main()
      File "/root/.ansible/tmp/ansible-tmp-1624643880.8584547-30710-199568632089406/AnsiballZ_netbox_ip_address.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/root/.ansible/tmp/ansible-tmp-1624643880.8584547-30710-199568632089406/AnsiballZ_netbox_ip_address.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.netbox.netbox.plugins.modules.netbox_ip_address', init_globals=None, run_name='__main__', alter_sys=True)
      File "/usr/lib/python3.8/runpy.py", line 207, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_netbox.netbox.netbox_ip_address_payload_i5g5k7ds/ansible_netbox.netbox.netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_ip_address.py", line 384, in <module>
      File "/tmp/ansible_netbox.netbox.netbox_ip_address_payload_i5g5k7ds/ansible_netbox.netbox.netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_ip_address.py", line 380, in main
      File "/tmp/ansible_netbox.netbox.netbox_ip_address_payload_i5g5k7ds/ansible_netbox.netbox.netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_ipam.py", line 206, in run
      File "/tmp/ansible_netbox.netbox.netbox_ip_address_payload_i5g5k7ds/ansible_netbox.netbox.netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_ipam.py", line 48, in _handle_state_new_present
      File "/tmp/ansible_netbox.netbox.netbox_ip_address_payload_i5g5k7ds/ansible_netbox.netbox.netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_ipam.py", line 84, in _ensure_ip_in_prefix_present_on_netif
    TypeError: 'RecordSet' object is not subscriptable
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

**Comment by sc68cal** [comment]
I prefer the 

```python
            self.nb_object = list(attached_ips)[-1].serialize()
```

style
