### ISSUE TITLE
Unexpected failure during module execution

### ISSUE THREAD

**Issue by Harrison-S1** [netbox-community/ansible_modules#577]
##### ISSUE TYPE
 - Bug Report

###### Ansible:

2.9.24
###### Netbox:

2.11.10
###### Collection:

3.1.1

###### pynetbox 
6.1.3
##### SUMMARY

Get the following error when trying to run the example play from: https://docs.ansible.com/ansible/latest/collections/netbox/netbox/netbox_device_module.html

```
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 147, in run
    res = self._execute()
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 665, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/action/normal.py", line 47, in run
    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/action/__init__.py", line 825, in _execute_module
    (module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/action/__init__.py", line 211, in _configure_module
    **become_kwargs)
  File "/usr/lib/python2.7/dist-packages/ansible/executor/module_common.py", line 1283, in modify_module
    environment=environment)
  File "/usr/lib/python2.7/dist-packages/ansible/executor/module_common.py", line 1120, in _find_module_utils
    py_module_cache, zf)
  File "/usr/lib/python2.7/dist-packages/ansible/executor/module_common.py", line 751, in recursive_finder
    [os.path.join(*py_module_name[:-idx])])
  File "/usr/lib/python2.7/dist-packages/ansible/executor/module_common.py", line 671, in __init__
    self.get_source()
  File "/usr/lib/python2.7/dist-packages/ansible/executor/module_common.py", line 686, in get_source
    pkg = import_module(self._package_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/dist-packages/ansible/utils/collection_loader.py", line 107, in load_module
    mod = self._find_module(fullname, None, load=True)[1]
  File "/usr/lib/python2.7/dist-packages/ansible/utils/collection_loader.py", line 247, in _find_module
    exec(code_object, newmod.__dict__)
  File "/home/ansible/.ansible/collections/ansible_collections/netbox/netbox/plugins/module_utils/netbox_dcim.py", line 9, in <module>
    from ansible_collections.netbox.netbox.plugins.module_utils.netbox_utils import (
  File "/usr/lib/python2.7/dist-packages/ansible/utils/collection_loader.py", line 107, in load_module
    mod = self._find_module(fullname, None, load=True)[1]
  File "/usr/lib/python2.7/dist-packages/ansible/utils/collection_loader.py", line 221, in _find_module
    code_object = compile(source=source, filename=source_path, mode='exec', flags=0, dont_inherit=True)
  File "/home/ansible/.ansible/collections/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 815
    f"One or more of the kwargs provided are invalid for {parent}, provided kwargs: {', '.join(sorted(provided_kwargs))}. Acceptable kwargs: {', '.join(sorted(acceptable_query_params))}"
                                                                                                                                                                                         ^
SyntaxError: invalid syntax
fatal: [localhost]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

##### STEPS TO REPRODUCE

Just installed the collection as normal 
pip install for pynetbox 

```
- name: "Test NetBox modules"
  connection: local
  hosts: localhost
  gather_facts: False
  vars:
    ansible_python_interpreter: /usr/bin/python3
  collections:
    - netbox.netbox

  tasks:

    - name: "Test Netbox interface module"
      netbox_device:
        netbox_url: https://FQDN
        netbox_token: REDACTED
        data:
          name: Test66
          device_type: Cisco Test
          device_role: Core Switch
          site: docks
        state: present
        validate_certs: false
```

##### EXPECTED RESULTS
Was expecting the play to add the device to the named site.

**Comment by rodvand** [comment]
Any reason you're using python2.7? Try with python 3.
