### ISSUE TITLE
Running every module get the same error

### ISSUE THREAD

**Issue by alexandregoncalves17** [netbox-community/ansible_modules#580]
Hello,

Versions:

pynetbox 6.1.3
ansible-core 2.11.4
python 3.9

I have seen some issues about this, but I didn't understand if is it solved or no. 

Could you please help me?

I got this error running every module:

![Screenshot 2021-08-26 at 17 33 57](https://user-images.githubusercontent.com/78537912/131001227-c8b41bbe-905a-46c5-a766-4730a26f14ed.png)

**Comment by Cylindric** [comment]
I don't suppose you know how I can get ansible-core <= 2.10? Doesn't seem to be in the pip repositories.

```
$ pip install "ansible-core<2.11"

ERROR: Could not find a version that satisfies the requirement ansible-core<2.11 (from versions: 0.0.1a1, 2.11.0b1, 2.11.0b2, 2.11.0b3, 2.11.0b4, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.11.1rc1, 2.11.1, 2.11.2rc1, 2.11.2, 2.11.3rc1, 2.11.3, 2.11.4rc1, 2.11.4)
ERROR: No matching distribution found for ansible-core<2.11
```

```
$ pip install "ansible-core~=2.10.0"

ERROR: Could not find a version that satisfies the requirement ansible-core~=2.10.0 (from versions: 0.0.1a1, 2.11.0b1, 2.11.0b2, 2.11.0b3, 2.11.0b4, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.11.1rc1, 2.11.1, 2.11.2rc1, 2.11.2, 2.11.3rc1, 2.11.3, 2.11.4rc1, 2.11.4)
ERROR: No matching distribution found for ansible-core~=2.10.0
```

**Comment by ThomasADavis** [comment]
At this time, no.  Our current plan is to fork the repo, do a bunch of git pulls/cherry picks, including this one:

https://github.com/netbox-community/ansible_modules/pull/558

and try to figure out how to install it..  lots of work, but not much choice.

I do need to submit a patch for the 'parent' device for interfaces..

**Comment by ThomasADavis** [comment]
Try this:

```
pip install ansible==2.10.7
```

should get you 2.10.7, which is the last version known to work..

**Comment by sc68cal** [comment]
I am running with the following in my `requirements.txt`

```
# https://github.com/netbox-community/ansible_modules/issues/529
ansible<4.0
```

This may help you.

**Comment by hferreira23** [comment]
@Cylindric ansible-core doesn't exist on the 2.10 version.

The 2.10.x core/base package for Ansible in 2.10 is called ansible-base. Starting on 2.11 the named was changed to ansible-core.

@ThomasADavis said that the last known version of Ansible to work was 2.10.7. This version runs on ansible-base 2.10.5.

So I'd say to try installing ansible-base 2.10.5 and install the netbox collection after that and see how it goes.

**Comment by sc68cal** [comment]
I have the Netbox modules working with Ansible version 3.4.0, via my requirements file capping it at `<4.0`:

```
$ pip freeze
<snip>
ansible==3.4.0
ansible-base==2.10.11
```

**Comment by ryanmerolle** [comment]
> At this time, no. Our current plan is to fork the repo, do a bunch of git pulls/cherry picks, including this one:
> 
> #558
> 
> and try to figure out how to install it.. lots of work, but not much choice.
> 
> I do need to submit a patch for the 'parent' device for interfaces..

Quick update here.

@nahun @sc68cal @gundalow @felixfontein @jeremystretch @rodvand & @daniel-wtd are all discussing what's needed to unblock ansible-core 2.11 and the CI requirements for ansible-collections.  We are slowly tackling these various issues.  I hope to see a collection bump soon to address this all, but I do not have a specific ETA.

**Comment by ryanmerolle** [comment]
@alexandregoncalves17 @Cylindric @hferreira23 @ThomasADavis @sc68cal 
We just cut a release for the collection version 3.1.2. Please update and let us know if you have any other issues.

**Comment by jayooin** [comment]
@ryanmerolle I just tested with the updated collection. It now works like a charm.
```
ansible            4.6.0
ansible-base       2.10.14
ansible-core       2.11.5
pynetbox           6.1.3
```

Thanks a lot!

**Comment by herpus-derpus** [comment]
@jayooin I tried your versions, 

`pip show ansible ansible-base ansible-core pynetbox | egrep '(Name|Version): '`

    Name: ansible
    Version: 4.6.0
    Name: ansible-base
    Version: 2.10.14
    Name: ansible-core
    Version: 2.11.5
    Name: pynetbox
    Version: 6.1.3

But I can't get it to work with our 

    NetBox v2.10.3

When I try to assign a free IP address from an IP Prefix like this:

    - name: "Create NetBox Object Entries"
      hosts:
        - "localhost"
      gather_facts: false
      tasks:
        - name: "Assign IPv4 Address in NetBox"
          netbox.netbox.netbox_ip_address:
              netbox_url: "https://my-netbox-v2-10-3.example.com"
              netbox_token: "my_hexidecimal_read_write_token"
              data:
                  dns_name: "service-env-role-01.example.com"
                  prefix: "10.9.8.0/23"
                  status: "Active"
                  tenant: "TLA"
            state: "new"
      delegate_to: "localhost"

I gets this:

```
task path: /home/my_username_here/repos/my_ansible_repo/playbooks/ad-hoc/netbox_an_ip.yml:7
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: my_username_here
<localhost> EXEC /bin/sh -c 'echo ~my_username_here && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/my_username_here/.ansible/tmp `"&& mkdir "` echo /home/my_username_here/.ansible/tmp/ansible-tmp-1736795918.470998-2963491-1667585247442 `" && echo ansible-tmp-1736795918.470998-2963491-1667585247442="` echo /home/my_username_here/.ansible/tmp/ansible-tmp-1736795918.470998-2963491-1667585247442 `" ) && sleep 0'
Using module file /home/my_username_here/.ansible/collections/ansible_collections/netbox/netbox/plugins/modules/netbox_ip_address.py
<localhost> PUT /home/my_username_here/.ansible/tmp/ansible-local-2963487x0c7yhe_/tmpev_0245b TO /home/my_username_here/.ansible/tmp/ansible-tmp-1736795918.470998-2963491-1667585247442/AnsiballZ_netbox_ip_address.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/my_username_here/.ansible/tmp/ansible-tmp-1736795918.470998-2963491-1667585247442/ /home/my_username_here/.ansible/tmp/ansible-tmp-1736795918.470998-2963491-1667585247442/AnsiballZ_netbox_ip_address.py && sleep 0'
<localhost> EXEC /bin/sh -c '/home/my_username_here/local/virtualenvs/ans_netbox/bin/python3 /home/my_username_here/.ansible/tmp/ansible-tmp-1736795918.470998-2963491-1667585247442/AnsiballZ_netbox_ip_address.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/my_username_here/.ansible/tmp/ansible-tmp-1736795918.470998-2963491-1667585247442/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/my_username_here/.ansible/tmp/ansible-tmp-1736795918.470998-2963491-1667585247442/AnsiballZ_netbox_ip_address.py", line 100, in <module>
    _ansiballz_main()
  File "/home/my_username_here/.ansible/tmp/ansible-tmp-1736795918.470998-2963491-1667585247442/AnsiballZ_netbox_ip_address.py", line 92, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/my_username_here/.ansible/tmp/ansible-tmp-1736795918.470998-2963491-1667585247442/AnsiballZ_netbox_ip_address.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.netbox.netbox.plugins.modules.netbox_ip_address', init_globals=dict(_module_fqn='ansible_collections.netbox.netbox.plugins.modules.netbox_ip_address', _modlib_path=modlib_path),
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code 
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/ansible_netbox.netbox.netbox_ip_address_payload_jgc1x7il/ansible_netbox.netbox.netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_ip_address.py", line 389, in <module>
  File "/tmp/ansible_netbox.netbox.netbox_ip_address_payload_jgc1x7il/ansible_netbox.netbox.netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_ip_address.py", line 385, in main
  File "/tmp/ansible_netbox.netbox.netbox_ip_address_payload_jgc1x7il/ansible_netbox.netbox.netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_ipam.py", line 206, in run
  File "/tmp/ansible_netbox.netbox.netbox_ip_address_payload_jgc1x7il/ansible_netbox.netbox.netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_ipam.py", line 52, in _handle_state_new_present
  File "/tmp/ansible_netbox.netbox.netbox_ip_address_payload_jgc1x7il/ansible_netbox.netbox.netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_ipam.py", line 105, in _get_new_available_ip_address
AttributeError: 'dict' object has no attribute 'serialize'
fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

Traceback (most recent call last):
  File "/home/my_username_here/.ansible/tmp/ansible-tmp-1736795918.470998-2963491-1667585247442/AnsiballZ_netbox_ip_address.py", line 100, in <module>
    _ansiballz_main() 
  File "/home/my_username_here/.ansible/tmp/ansible-tmp-1736795918.470998-2963491-1667585247442/AnsiballZ_netbox_ip_address.py", line 92, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/my_username_here/.ansible/tmp/ansible-tmp-1736795918.470998-2963491-1667585247442/AnsiballZ_netbox_ip_address.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.netbox.netbox.plugins.modules.netbox_ip_address', init_globals=dict(_module_fqn='ansible_collections.netbox.netbox.plugins.modules.netbox_ip_address', _modlib_path=modlib_path),
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/ansible_netbox.netbox.netbox_ip_address_payload_jgc1x7il/ansible_netbox.netbox.netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_ip_address.py", line 389, in <module>
  File "/tmp/ansible_netbox.netbox.netbox_ip_address_payload_jgc1x7il/ansible_netbox.netbox.netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_ip_address.py", line 385, in main
  File "/tmp/ansible_netbox.netbox.netbox_ip_address_payload_jgc1x7il/ansible_netbox.netbox.netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_ipam.py", line 206, in run
  File "/tmp/ansible_netbox.netbox.netbox_ip_address_payload_jgc1x7il/ansible_netbox.netbox.netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_ipam.py", line 52, in _handle_state_new_present
  File "/tmp/ansible_netbox.netbox.netbox_ip_address_payload_jgc1x7il/ansible_netbox.netbox.netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_ipam.py", line 105, in _get_new_available_ip_address
AttributeError: 'dict' object has no attribute 'serialize'
```
