### ISSUE TITLE
On collection v3.5.0 - '>' not supported between instances of 'NoneType' and 'int' error

### ISSUE THREAD

**Issue by m-kratochvil** [netbox-community/ansible_modules#694]
##### ISSUE TYPE
Bug Report

###### Ansible:
2.10.13

###### NetBox:
2.9.3

###### Collection:
netbox.netbox collection 3.5.0

###### pynetbox
$ pip3 list | grep pynetbox
pynetbox           6.1.2

##### SUMMARY
After netbox.netbox collection upgrade from 3.4.0 to 3.5.0, fetching inventory from Netbox fails with following error:
```
  File "/Users/xxxxxxxx/.ansible/collections/ansible_collections/netbox/netbox/plugins/inventory/nb_inventory.py", line 879, in refresh_sites_lookup
    if site["prefix_count"] > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

##### STEPS TO REPRODUCE
While the below is a custom environment, it shows the components involved and how we reproduce the failure.

```
user@prompt# ANSIBLE_INVENTORY_ENABLED='netbox.netbox.nb_inventory,netbox_additionals,yaml' ANSIBLE_INVENTORY_PLUGINS='./plugins/inventories/' ANSIBLE_INVENTORY='/var/folders/bd/g3t3n4g5141_ytvysfys0x_w0000gn/T/netboxma1v_a8j/device-type.yaml,inventories/netbox_additionals.yaml,inventories/globals.yaml' ansible-inventory -vvvv -y --list --export --output inventories/directory/file.yaml
ansible-inventory 2.10.13
  config file = /Users/xxxxxxxx/devel/repository/ansible.cfg
  configured module search path = ['/Users/xxxxxxxx/devel/repository/plugins/modules']
  ansible python module location = /Users/xxxxxxxx/.pyenv/versions/3.9.5/envs/repository/lib/python3.9/site-packages/ansible
  executable location = /Users/xxxxxxxx/.pyenv/versions/repository/bin/ansible-inventory
  python version = 3.9.5 (default, Jun 15 2021, 10:31:18) [Clang 12.0.5 (clang-1205.0.22.9)]
Using /Users/xxxxxxx/devel/repository/ansible.cfg as config file
setting up inventory plugins
Loading collection netbox.netbox from /Users/xxxxxxx/.ansible/collections/ansible_collections/netbox/netbox
Fetching: https://netbox.url/api/status
Fetching: https://netbox.url/api/docs/?format=openapi
Fetching: https://netbox.url/api/dcim/devices/?limit=0&status=active&status=staged&tenant=tenant01&tenant=tenant02&tenant=tenant03&region=region01&role=router&exclude=config_context
Fetching: https://netbox.url/api/virtualization/virtual-machines/?limit=0&status=active&status=staged&tenant=tenant01&tenant=tenant02&tenant=tenant03&region=region01&role=router&exclude=config_context
Fetching: https://netbox.url/api/dcim/sites/?limit=0
Fetching: https://netbox.url/api/dcim/regions/?limit=0
Fetching: https://netbox.url/api/tenancy/tenants/?limit=0
Fetching: https://netbox.url/api/dcim/racks/?limit=0
Fetching: https://netbox.url/api/dcim/rack-groups/?limit=0
Fetching: https://netbox.url/api/dcim/device-roles/?limit=0
Fetching: https://netbox.url/api/dcim/platforms/?limit=0
Fetching: https://netbox.url/api/dcim/device-types/?limit=0
Fetching: https://netbox.url/api/virtualization/clusters/?limit=0
Fetching: https://netbox.url/api/dcim/manufacturers/?limit=0
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/xxxxxxx/.pyenv/versions/3.9.5/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/Users/xxxxxxx/.pyenv/versions/3.9.5/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/xxxxxxx/.ansible/collections/ansible_collections/netbox/netbox/plugins/inventory/nb_inventory.py", line 1274, in wrapper
    raise e
  File "/Users/xxxxxxx/.ansible/collections/ansible_collections/netbox/netbox/plugins/inventory/nb_inventory.py", line 1269, in wrapper
    lookup()
  File "/Users/xxxxxxx/.ansible/collections/ansible_collections/netbox/netbox/plugins/inventory/nb_inventory.py", line 879, in refresh_sites_lookup
    if site["prefix_count"] > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
Parsed /var/folders/bd/g3t3n4g5141_ytvysfys0x_w0000gn/T/netboxma1v_a8j/router.yaml inventory source with netbox_additionals plugin
setting up inventory plugins
Parsed /Users/xxxxxxx/devel/repository/ci/inventories/netbox_additionals.yaml inventory source with netbox_additionals plugin
setting up inventory plugins
Parsed /Users/xxxxxxx/devel/repository/ci/inventories/globals.yaml inventory source with netbox_additionals plugin
```

##### EXPECTED RESULTS
The inventory should be fetched from Netbox without failing.

##### ACTUAL RESULTS
The inventory dump fails as shown above.
```
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

**Comment by rodvand** [comment]
Could you post you inventory configuration? Just remove any API tokens or URLs you don't want us to see.

**Comment by rodvand** [comment]
I don't have a NetBox version 2.9 readily available, could you find a Site with no prefixes and look at the API representation of it? `/api/dcim/sites/<site ID>`

**Comment by rodvand** [comment]
I have located the issue. In earlier versions of NetBox the `prefix_count` is `null` when no prefixes are assigned a site. In the later versions it is 0. I'll have a patch out for this issue in not that long.

**Comment by m-kratochvil** [comment]
@rodvand 
Sorry for the late reply, I was already offline when you responded. And thank you very much for quick resolution, much appreciated!
