### ISSUE TITLE
Bug: netbox_prefix: Invalid vlan_group key for vlan filter

### ISSUE THREAD

**Issue by vsvetlov** [netbox-community/ansible_modules#85]
Hello,

I have a VLAN with the same ID in two different VLAN Groups.
Trying to create a prefix with mapping to this VLAN results in the following error:

Traceback:
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1581424930.1219447-139266201143184/AnsiballZ_netbox_prefix.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1581424930.1219447-139266201143184/AnsiballZ_netbox_prefix.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1581424930.1219447-139266201143184/AnsiballZ_netbox_prefix.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.fragmentedpacket.netbox_modules.plugins.modules.netbox_prefix', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_netbox_prefix_payload_3dyfcsgu/ansible_netbox_prefix_payload.zip/ansible_collections/fragmentedpacket/netbox_modules/plugins/modules/netbox_prefix.py", line 269, in <module>
  File "/tmp/ansible_netbox_prefix_payload_3dyfcsgu/ansible_netbox_prefix_payload.zip/ansible_collections/fragmentedpacket/netbox_modules/plugins/modules/netbox_prefix.py", line 264, in main
  File "/tmp/ansible_netbox_prefix_payload_3dyfcsgu/ansible_netbox_prefix_payload.zip/ansible_collections/fragmentedpacket/netbox_modules/plugins/module_utils/netbox_ipam.py", line 39, in __init__
  File "/tmp/ansible_netbox_prefix_payload_3dyfcsgu/ansible_netbox_prefix_payload.zip/ansible_collections/fragmentedpacket/netbox_modules/plugins/module_utils/netbox_utils.py", line 430, in __init__
  File "/tmp/ansible_netbox_prefix_payload_3dyfcsgu/ansible_netbox_prefix_payload.zip/ansible_collections/fragmentedpacket/netbox_modules/plugins/module_utils/netbox_utils.py", line 601, in _find_ids
  File "/usr/local/lib/python3.7/dist-packages/pynetbox/core/endpoint.py", line 142, in get
    "get() returned more than one result. "
ValueError: get() returned more than one result. Check that the kwarg(s) passed are valid for this endpoint or use filter() or all() instead.

Module arguments:
  tasks:
    - name: Create prefix within Netbox with only required information
      netbox_prefix:
        netbox_url: http://192.168.56.101:32774/
        netbox_token: 0123456789abcdef0123456789abcdef01234567
        data:
          prefix: 10.156.0.0/19
          site: US2
          prefix_role: services
          vlan:
            name: vlan10
            vlan_group: vgroup1
            site: US2
        state: present

At ngnix side it looks like 
netbox_1         | 172.19.0.7 - - [10/Feb/2020:01:30:26 +0000] "GET /api/ipam/vlans/?name=vlan10&site_id=1&vlan_group_id=1 HTTP/1.0" 200 1012 "-" "python-requests/2.21.0"

For some reasons it uses vlan_group_id=1 instead of group_id=1.

I can see _convert_identical_keys function for pynetbox but it looks like this error is triggered somewhere earlier in module.

**Comment by FragmentedPacket** [comment]
Thanks for reporting this. I think I know where this is happening. I need to use the self._convert_identical_keys when attempting to find the IDs when the value is a dictionary (such as your vlan key.
```
vlan:
  name: vlan10
  vlan_group: vgroup1
  site: US2
```
Should be converted before searching for it to:
```
vlan:
  name: vlan10
  group: vgroup1
  site: US2
```

I will get a PR for this in today and then if you can test, that would be great. I will reply back once the PR is submitted.

**Comment by FragmentedPacket** [comment]
@vsvetlov Can you test PR#86 and let me know if that fixes your issue?

**Comment by vsvetlov** [comment]
Thank you for the quick answer!

Unfortunately, it does not work! nginx side:
netbox_1         | 172.19.0.7 - - [11/Feb/2020:22:23:10 +0000] "GET /api/ipam/vlans/?site_id=1&name=vlan10 HTTP/1.0" 200 1012 "-" "python-requests/2.21.0"

Sorry I forgot to mention that "vlan_group" and "vid" are missed in ALLOWED_QUERY_PARAMS and I modified it in my setup. Anyway it seems it does not handle "vlan_group" at all.
Might be the vlan_group arg goes over _convert_identical_keys before being processed by ALLOWED_QUERY_PARAMS?


Traceback
File "/tmp/ansible_netbox_prefix_payload_vnp_oyc9/ansible_netbox_prefix_payload.zip/ansible_collections/netbox_community/ansible_modules/plugins/module_utils/netbox_utils.py", line 460, in _nb_endpoint_get
    response = nb_endpoint.get(**query_params)
  File "/usr/local/lib/python3.7/dist-packages/pynetbox/core/endpoint.py", line 142, in get
    "get() returned more than one result. "

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "data": {
                "custom_fields": null,
                "description": null,
                "family": null,
                "is_pool": null,
                "parent": null,
                "prefix": "10.156.0.0/19",
                "prefix_length": null,
                "prefix_role": "services",
                "site": "US2",
                "status": null,
                "tags": null,
                "tenant": null,
                "vlan": {
                    "group": "vgroup2",
                    "name": "vlan10",
                    "site": "us2"
                },
                "vrf": null
            },
            "first_available": null,
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "netbox_url": "http://192.168.56.101:32777/",
            "state": "present",
            "validate_certs": true
        }
    },
    "msg": "More than one result returned for vlan"
}

**Comment by FragmentedPacket** [comment]
The PR has been updated. I think it should work now. The only caveat that I have noticed is the vlan_group provided gets converted to slug and if two vlan groups exist with the same slug, it will probably fail. I think at that point using the lookup plugin and passing the integer in for either the vlan or the vlan_group will be necessary.

**Comment by vsvetlov** [comment]
It works perfectly! Thank you!

Netbox does not allow to create the vlan_groups with the same name within the same site.
I tested a case with two vlan_groups with the same names and the same slug but in different sites and it also works correctly.

**Comment by FragmentedPacket** [comment]
I appreciate all your feedback and help! Thanks for submitting the bug report and testing!
