### ISSUE TITLE
[Bug]: Broken idempotency for `netbox_cable` module

### ISSUE THREAD

**Issue by jof** [netbox-community/ansible_modules#989]
### Ansible NetBox Collection version

devel branch

### Ansible version

```bash
ansible [core 2.14.4]
  config file = /home/jof/src/netbox-community/ansible_modules/ansible.cfg
  configured module search path = ['/home/jof/src/netbox-community/ansible_modules/plugins/modules']
  ansible python module location = /home/jof/.local/share/virtualenvs/ansible_modules-9A3mb43w/lib/python3.10/site-packages/ansible
  ansible collection location = /home/jof/src/netbox-community/ansible_modules/ansible_collections
  executable location = /home/jof/.local/share/virtualenvs/ansible_modules-9A3mb43w/lib/python3.10/site-packages/ansible/cli/adhoc.py
  python version = 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] (/home/jof/.local/share/virtualenvs/ansible_modules-9A3mb43w/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

### NetBox version

v3.4.8

### Python version

3.10

### Steps to Reproduce

Broadly:
- Create a `netbox.netbox.netbox_cable` in Netbox, connecting a dcim.interface to a dcim.rearport
   - See that it was successful
- Re-run the same Ansible calling `netbox.netbox.netbox_cable` with the same arguments
   - See that this causes and displays a stacktrace / uncaught exception

An example Exception:
```
The full traceback is:
Traceback (most recent call last):
  File "/home/jof/.ansible/tmp/ansible-tmp-1682535213.9534392-31234-35478953661076/AnsiballZ_netbox_cable.py", line 259, in <module>
    _ansiballz_main()
  File "/home/jof/.ansible/tmp/ansible-tmp-1682535213.9534392-31234-35478953661076/AnsiballZ_netbox_cable.py", line 249, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/jof/.ansible/tmp/ansible-tmp-1682535213.9534392-31234-35478953661076/AnsiballZ_netbox_cable.py", line 122, in invoke_module
    runpy.run_module(mod_name='ansible.modules.netbox_cable', init_globals=dict(_module_fqn='ansible.modules.netbox_cable', _modlib_path=modlib_path),
  File "/usr/lib/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_netbox_cable_payload_dld6lzt0/ansible_netbox_cable_payload.zip/ansible/modules/netbox_cable.py", line 364, in <module>
  File "/tmp/ansible_netbox_cable_payload_dld6lzt0/ansible_netbox_cable_payload.zip/ansible/modules/netbox_cable.py", line 360, in main
  File "/tmp/ansible_netbox_cable_payload_dld6lzt0/ansible_netbox_cable_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_dcim.py", line 229, in run
  File "/tmp/ansible_netbox_cable_payload_dld6lzt0/ansible_netbox_cable_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 1400, in _ensure_object_exists
  File "/tmp/ansible_netbox_cable_payload_dld6lzt0/ansible_netbox_cable_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 1354, in _update_netbox_object
  File "/tmp/ansible_netbox_cable_payload_dld6lzt0/ansible_netbox_cable_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 1344, in _convert_termination
  File "/tmp/ansible_netbox_cable_payload_dld6lzt0/ansible_netbox_cable_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 1078, in _find_app
Exception: rear-ports not found in API_APPS_ENDPOINTS
```

The `_convert_termination()` helper in `NetboxModule._update_netbox_object` looks for an app name in `API_APPS_ENDPOINTS` based on the name of the existing termination API endpoint. My latest netbox uses rear-ports (for example `/dcim/rear-ports/7/`), and the values of `API_APPS_ENDPOINTS` in `module_utils.py` only seems to list snake_case values (e.g. "rear_ports").

### Expected Behavior

Re-running `netbox_cable` with the same arguments, when a matching cable already exists, should exit successfully with "changed": "false" in the module output.

### Observed Behavior

An Exception is raised :(

**Comment by jof** [comment]
Hrm.... I wasn't actually properly testing against `devel`, and it was pulling in `netbox.netbox` from the ansible distribution.

This seems to work correctly against the current tip of `devel`.

**Comment by jof** [comment]
Without knowing the internals of this module too deeply, I'm experimenting with a patch like:

```diff
diff --git a/plugins/module_utils/netbox_utils.py b/plugins/module_utils/netbox_utils.py
index ce1b646..4b69ba7 100644
--- a/plugins/module_utils/netbox_utils.py
+++ b/plugins/module_utils/netbox_utils.py
@@ -70,6 +70,7 @@ API_APPS_ENDPOINTS = dict(
         "rack_groups",
         "rack_roles",
         "rear_ports",
+        "rear-ports",
         "rear_port_templates",
         "regions",
         "sites",
@@ -346,6 +347,7 @@ ENDPOINT_NAME_MAPPING = {
     "rack_groups": "rack_group",
     "rack_roles": "rack_role",
     "rear_ports": "rear_port",
+    "rear-ports": "rearport",
     "rear_port_templates": "rear_port_template",
     "regions": "region",
     "rirs": "rir",
```

This seems to fix the issue, but I made these changes with debugging and adding things that "felt" missing. I'm not sure I understand all of the uses and expectations of the `ENDPOINT_NAME_MAPPING` structure to know if this is the proper fix or not.
